[build]
  functions = "functions"

[[redirects]]
  from = "/sitemap.xml"
  to = "/.netlify/functions/sitemap"
  status = 200

[[redirects]]
  from = "/movies.xml"
  to = "/.netlify/functions/sitemap?type=movies"
  status = 200

[[redirects]]
  from = "/series.xml"
  to = "/.netlify/functions/sitemap?type=series"
  status = 200
  
